version: "3.7"

services:
  broker-service:
    image: masulo1212/todo-amd64:1.0.0 # 注意平台
    ports:
      - "9090:9090"
    environment:
      DSN: "host=postgres port=5432 user=root password=secret dbname=todoDB sslmode=disable timezone=UTC connect_timeout=5"
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: "postgres:14.0"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
      # placement:
      #   constraints:
      #     - node.hostname == node-1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todoDB
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
